import{a as S,S as q,i as l}from"./assets/vendor-Dy2ZTtfi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const C="51385266-59a206174458b904205f7b7fa";async function m(s,t=1){try{return(await S("https://pixabay.com/api/",{params:{key:C,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}catch(o){console.log(o.message)}}let d=null;const u=document.querySelector(".gallery"),p=document.querySelector(".loader"),h=document.querySelector(".loader-container"),g=document.querySelector(".loader-more"),y=document.querySelector(".loader-more-container"),b=document.querySelector(".btn-load-more");function P(s){return s.map(({webformatURL:t,largeImageURL:o,tags:a,likes:e,views:r,comments:i,downloads:M})=>`
      <div class="wrap">
        <a class="gallery-item" href="${o}">
          <img class="img" src="${t}" alt="${a}" width="360px">
        </a>
        <ul class="list">
          <li class="list-item"><p class="label">Likes</p><p class="value">${e}</p></li>
          <li class="list-item"><p class="label">Views</p><p class="value">${r}</p></li>
          <li class="list-item"><p class="label">Comments</p><p class="value">${i}</p></li>
          <li class="list-item"><p class="label">Downloads</p><p class="value">${M}</p></li>
        </ul>
      </div>
    `).join("")}function v(s,t=!1){const o=P(s);t?u.insertAdjacentHTML("beforeend",o):u.innerHTML=o,d?d.refresh():d=new q(".gallery a",{captionsData:"alt",captionDelay:250})}function _(){u.innerHTML=""}function E(){p.classList.remove("hidden"),h.style.display="flex"}function A(){p.classList.add("hidden"),h.style.display="none"}function R(){g.classList.remove("hidden"),y.style.display="flex"}function $(){g.classList.add("hidden"),y.style.display="none"}function L(){b.classList.remove("hidden")}function f(){b.classList.add("hidden")}const w=document.querySelector(".form"),B=document.querySelector(".btn-load-more");w.addEventListener("submit",G);B.addEventListener("click",H);let n=1,c="",x=0;async function G(s){if(s.preventDefault(),c=s.target.elements["search-text"].value.trim(),n=1,c===""){l.warning({message:"Unfortunately you cannot leave the input blank",position:"topRight",messageColor:"#fff",titleColor:"#fff",color:"#ef4040",iconUrl:"./img/bi_x-octagon-2.svg",maxWidth:432});return}_(),E();try{const t=await m(c);if(x=t.totalHits,!t.hits||t.hits.length===0){l.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",messageColor:"#fff",titleColor:"#fff",color:"#ef4040",iconUrl:"./img/bi_x-octagon-2.svg",maxWidth:432}),f();return}v(t.hits),L(),w.reset()}catch{l.show({message:"Sorry, something went wrong. Please try again!",position:"topRight",messageColor:"#fff",titleColor:"#fff",color:"#ef4040",iconUrl:"./img/bi_x-octagon-2.svg",maxWidth:432})}finally{A()}}async function H(){n++,f(),R();const t=Math.ceil(x/15);try{if(n>t){l.show({message:"We are sorry, but you haveve reached the end of search results.",position:"topRight",messageColor:"#fff",titleColor:"#fff",color:"#ef4040",iconUrl:"./img/bi_x-octagon-2.svg",maxWidth:432}),f();return}const o=await m(c,n);v(o.hits,!0);const e=document.querySelector(".wrap").getBoundingClientRect().height;window.scrollBy({top:e*6,behavior:"smooth"}),L()}catch(o){alert(o.message)}finally{$()}}
//# sourceMappingURL=index.js.map
