import{a as S,S as P,i as c}from"./assets/vendor-Dy2ZTtfi.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const E="51385266-59a206174458b904205f7b7fa";async function p(a,e=1){try{return(await S("https://pixabay.com/api/",{params:{key:E,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})).data}catch(s){console.log(s.message)}}let f=null;const u=document.querySelector(".gallery"),g=document.querySelector(".loader"),h=document.querySelector(".loader-container"),y=document.querySelector(".loader-more"),b=document.querySelector(".loader-more-container"),L=document.querySelector(".btn-load-more");function _(a){return a.map(({webformatURL:e,largeImageURL:s,tags:o,likes:t,views:r,comments:l,downloads:M})=>`
      <div class="wrap">
        <a class="gallery-item" href="${s}">
          <img class="img" src="${e}" alt="${o}" width="360px">
        </a>
        <ul class="list">
          <li class="list-item"><p class="label">Likes</p><p class="value">${t}</p></li>
          <li class="list-item"><p class="label">Views</p><p class="value">${r}</p></li>
          <li class="list-item"><p class="label">Comments</p><p class="value">${l}</p></li>
          <li class="list-item"><p class="label">Downloads</p><p class="value">${M}</p></li>
        </ul>
      </div>
    `).join("")}function v(a,e={}){const{append:s=!1}=e,o=_(a);s?u.insertAdjacentHTML("beforeend",o):u.innerHTML=o,f?f.refresh():f=new P(".gallery a",{captionsData:"alt",captionDelay:250})}function C(){u.innerHTML=""}function q(){g.classList.remove("hidden"),h.style.display="flex"}function A(){g.classList.add("hidden"),h.style.display="none"}function G(){y.classList.remove("hidden"),b.style.display="flex"}function R(){y.classList.add("hidden"),b.style.display="none"}function w(){L.classList.remove("hidden")}function n(){L.classList.add("hidden")}const x=document.querySelector(".form"),I=document.querySelector(".btn-load-more");x.addEventListener("submit",$);I.addEventListener("click",B);let i=1,d="",m=0;async function $(a){if(a.preventDefault(),n(),d=a.target.elements["search-text"].value.trim(),i=1,d===""){c.warning({message:"Unfortunately you cannot leave the input blank",position:"topRight",messageColor:"#fff",titleColor:"#fff",color:"#ef4040",iconUrl:"./img/bi_x-octagon-2.svg",maxWidth:432});return}C(),q();try{const e=await p(d,i);if(m=e.totalHits,!e.hits||e.hits.length===0){c.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",messageColor:"#fff",titleColor:"#fff",color:"#ef4040",iconUrl:"./img/bi_x-octagon-2.svg",maxWidth:432}),n();return}v(e.hits);const o=Math.ceil(m/15);i<o?w():n(),x.reset()}catch{c.show({message:"Sorry, something went wrong. Please try again!",position:"topRight",messageColor:"#fff",titleColor:"#fff",color:"#ef4040",iconUrl:"./img/bi_x-octagon-2.svg",maxWidth:432})}finally{A()}}async function B(){i++,n(),G();const e=Math.ceil(m/15);try{if(console.log(i),console.log(e),i>=e){c.show({message:"We are sorry, but you haveve reached the end of search results.",position:"topRight",messageColor:"#fff",titleColor:"#fff",color:"#ef4040",iconUrl:"./img/bi_x-octagon-2.svg",maxWidth:432}),n();return}const s=await p(d,i);v(s.hits,{append:!0});const o=document.querySelector(".gallery .wrap"),t=(o==null?void 0:o.getBoundingClientRect().height)||0;window.scrollBy({top:t*2,behavior:"smooth"}),i<e?w():n()}catch{c.show({message:"Sorry, something went wrong. Please try again!",position:"topRight",messageColor:"#fff",titleColor:"#fff",color:"#ef4040",iconUrl:"./img/bi_x-octagon-2.svg",maxWidth:432})}finally{R()}}
//# sourceMappingURL=index.js.map
